name: "Build and Publish Docker Image"
description: "Build and publish Docker image to GHCR, with version tags based on package version"

runs:
   using: "composite"
   steps:
      - uses: martinbeentjes/npm-get-version-action@main
        id: package-version
      - run: echo This will be release ${{ steps.package-version.outputs.current-version}}
        shell: bash
      - uses: booxmedialtd/ws-action-parse-semver@v1
        id: semver
        with:
            input_string: ${{ steps.package-version.outputs.current-version }}
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ github.token }}
      - name: Build and publish
        uses: docker/build-push-action@v4
        with:
            context: .
            push: true
            tags: |
               ghcr.io/${{ github.repository }}:latest
               ghcr.io/${{ github.repository }}:${{ steps.semver.outputs.major }}
               ghcr.io/${{ github.repository }}:${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}
               ghcr.io/${{ github.repository }}:${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.${{ steps.semver.outputs.patch }}
               ghcr.io/${{ github.repository }}:${{ steps.semver.outputs.fullversion }}
